### ISSUE TITLE
utf-8 en-/decoding

### ISSUE THREAD

**Issue by solarjoe** [sjschneider/py3samsdk#2]
I think your module has a similar issue than I had a while ago. 
Not all functions that return `c_char_p` are working without manually de- or encoding.
E.g. say I want to get the module name or description like you did in `get_modules()`:

```
mod_name = self.entry_name(entry).decode('utf-8')
mod_desc = self.entry_description(entry).decode('utf-8')
```
I am still thinking about a nice way to completly hide this from the user, but couldn't come up with a nice solution so far. 
Decorators?

**Comment by sjschneider** [comment]
Hi @solarjoe, thanks for the inquiry and suggestion.  If I understand your question, it seems to me that a straight forward approach would be to add decode('utf-8') to the relevant methods, including entry_name() and entry_description() rather than calling them in the get_modules() method?

The only downside I can see of using a decorator here is that we would need to check datatypes and/or if the decode() function exists at runtime.  Thoughts?

Either way, I agree some improvement in consistency would be welcome.

**Comment by solarjoe** [comment]
Yes, correct that would be straight forward. This is how I fixed the first wrapper published by NREL. But I am still thinking about a more beautiful way :)
What do you mean with 
> if the decode() function exists at runtime
?

But could a decorator handle the differences between Python 2 and 3 automatically?

**Comment by solarjoe** [comment]
Here is a first snipped on a decorator that seems to work. Of course we have to check the datatypes, but that's quite simple.
The decorator converts input and output if necessary.
Having that decorator, it is quite easy to add a line to it so it will handle Python 2 and 3 code correctly.

I guess we could change `for a in args` to a list comprehension, then we have the full beauty.

Then we could put it back into the SDK and let them adjust the code on new releases. :)

```python
    def p_decorate(func):
        def func_wrapper(*args):
            args_conv = []
            for a in args:
                if isinstance(a, str):
                    args_conv.append(a.encode('ascii'))
                else:
                    args_conv.append(a)
            print(args_conv)

            rv = func(*args_conv)
            print(type(rv))
            if isinstance(rv, bytes):
                #one module returns a invalid utf character, 'replace' 'ignore' 'backslashreplace'
                return rv.decode('utf-8', 'ignore') # .decode('utf-8', 'ignore')
            else:
                return rv

        return func_wrapper


    @p_decorate
    def module_create_orig(self,name):
        self.pdll.ssc_module_create.restype = c_void_p
        return self.pdll.ssc_module_create( c_char_p(name) )

    @p_decorate
    def info_name(self, p_inf):
        self.pdll.ssc_info_name.restype = c_char_p
        return self.pdll.ssc_info_name(c_void_p(p_inf))

    @p_decorate
    def info_label(self, p_inf):
        self.pdll.ssc_info_label.restype = c_char_p
        return self.pdll.ssc_info_label(c_void_p(p_inf))

```

**Comment by solarjoe** [comment]
```python
    def p_decorate(func):
        def func_wrapper(*args):

            # this syntax works in Python 2.5+
            args_conv = [a.encode('ascii') if isinstance(a, str) else a for a in args]

            rv = func(*args_conv)

            if isinstance(rv, bytes):
                #one module returns a invalid utf character, 'replace' 'ignore' 'backslashreplace'
                return rv.decode('utf-8', 'ignore') # .decode('utf-8', 'ignore')
            else:
                return rv

        return func_wrapper
```

**Comment by solarjoe** [comment]
This decorator should work for Python 2 and 3:
```python
    def p_decorate(func):
        def func_wrapper(*args):

            if sys.version_info.major > 2:

                # this syntax works in versions 2.5+
                args_conv = [a.encode('ascii') if isinstance(a, str) else a for a in args]

                rv = func(*args_conv)

                if isinstance(rv, bytes):
                    #one module returns a invalid utf character, 'replace' 'ignore' 'backslashreplace'
                    return rv.decode('utf-8', 'ignore') # .decode('utf-8', 'ignore')
                else:
                    return rv

            else:
                rv = func(*args)

        return func_wrapper
```

**Comment by solarjoe** [comment]
I modified the original wrapper from sam-sdk-2016-3-14-r3 with the decorator and some other minor changes.

https://gist.github.com/solarjoe/fc9a6391c1b8201750b923b04995bceb

**Comment by sjschneider** [comment]
Thanks very much for this @solarjoe.  Your suggestion is great and your code elegant.  I'll try to integrate these within the next week or so unless you'd like to make them yourself.  I'd also like to set up integration testing for both the Python 2 and 3 environments.

I've had a conversation with the NREL team about this already and I agree that the best solution is for them to maintain the code and release it with the SDK.  Part of the benefit of this package, though, is the inclusion of testing and that it is a module.

**Comment by sjschneider** [comment]
@solarjoe I've added your decorator code and made the necessary modifications.  Works like a charm!  I haven't tested this on Python 2 yet, so I'm not updating the doc yet.
