### ISSUE TITLE
Install SAM python into Anaconda

### ISSUE THREAD

**Issue by stepanenkopaul** [sjschneider/py3samsdk#4]
maybe somebody knows how install SAM python into Anaconda? I try install python module from https://github.com/sjschneider/py3samsdk, but all what i get it's this error: package directory 'py3samsdk' does not exist

**Comment by sjschneider** [comment]
You should be able to install via pip:

    pip install https://github.com/sjschneider/py3samsdk/archive/master.zip

**Comment by sjschneider** [comment]
Do make sure that you are using your conda environment's pip.  To be sure, you can activate your conda environment with:

    source activate CONDA_ENVIRONMENT

or check which version of pip you are using

    which pip
or

    pip --version
